version: "3.8"
services:
  api:
    build: .
    image: dice-api-image:v1
    container_name: diceApi-container
    ports:
      - "8080:8080"
    networks:
      - diceApi-net
    depends_on:
      - db
    environment:
      DB_URL: mongodb://db/diceGame
  db:
    image: mongo:4.0-xenial
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - diceGame:/data/db
    networks:
      - diceApi-net

volumes:
  diceGame:

networks:
  diceApi-net:
    driver: bridge
